export const PANE_NODEINFO = 'PANE_NODEINFO'
export const PANE_STAKINGINFO = 'PANE_STAKINGINFO'
export const PANE_GENERALINFO = 'PANE_GENERALINFO'
export const PANE_IMPORTKEYS = 'PANE_IMPORTKEYS'
export const PANE_EXPORTKEYS = 'PANE_EXPORTKEYS'
export const PANE_RESCAN = 'PANE_RESCAN'
export const DEFAULT_PANE = PANE_NODEINFO
